In [1]:
import numpy as np

In [4]:
np.random.seed(20)
np.random.randint(20,1000,12)

array([375, 494, 291, 243, 944, 238, 413, 424, 863, 810, 603, 182])

In [5]:
np.random.randint(20,1000,(3,5))

array([[138, 572, 489, 494, 814],
       [783, 999, 804, 785, 762],
       [762, 210, 164, 637, 889]])

In [6]:
x=np.random.randint(20,1000,12)
np.sin(x)

array([-0.17613497,  0.71485535, -0.99388533,  0.76255845,  0.39595283,
        0.64358428, -0.98516179,  0.10607744, -0.80643623,  0.99646158,
       -0.90555279,  0.05305349])

In [10]:
np.exp(2)# universal function

7.38905609893065

In [9]:
np.e**2 # a constant

7.3890560989306495

In [15]:
def logistic(x,threshold=0.5):
    x=np.array(x)
    y=1/(1+np.e**(-x))
    print(y)
    return y>=threshold

In [16]:
logistic([2,4,3,5,7,8,5,3])

[0.88079708 0.98201379 0.95257413 0.99330715 0.99908895 0.99966465
 0.99330715 0.95257413]


array([ True,  True,  True,  True,  True,  True,  True,  True])

In [18]:
logistic([2,4,3,5,7,8,5,3],0.99)

[0.88079708 0.98201379 0.95257413 0.99330715 0.99908895 0.99966465
 0.99330715 0.95257413]


array([False, False, False,  True,  True,  True,  True, False])

In [22]:
logistic([-2000,49377736,3,5,7,8455266,5,39973],0.7)

[0.         1.         0.95257413 0.99330715 0.99908895 1.
 0.99330715 1.        ]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in power
  This is separate from the ipykernel package so we can avoid doing imports until


array([False,  True,  True,  True,  True,  True,  True,  True])

In [23]:
def logistic(x,threshold=0.5):
    x=np.array(x)
    y=1/(1+np.e**(-x))
    print(y)
    return np.where(y>=threshold,1,0)

In [24]:
logistic([-2000,49377736,3,5,7,8455266,5,39973],0.7)

[0.         1.         0.95257413 0.99330715 0.99908895 1.
 0.99330715 1.        ]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in power
  This is separate from the ipykernel package so we can avoid doing imports until


array([0, 1, 1, 1, 1, 1, 1, 1])